env:
  browser: true
  es2021: true
  node: true
ignorePatterns:
  - dist
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - react
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  '@typescript-eslint/no-explicit-any':
    - off
  '@typescript-eslint/no-unused-vars':
    - error
    - varsIgnorePattern: '^_'
      argsIgnorePattern: '^_'
  'react/react-in-jsx-scope':
    - off